version: "3.9"
services:
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  auth:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/login-service
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
  nagios:
    image: jasonrivers/nagios:latest
    ports:
      - "8080:80"
      - "5666:5666"
    environment:
      - NAGIOS_FQDN=nagios.example.com
      - NAGIOSADMIN_USER=nagiosadmin
      - NAGIOSADMIN_PASS=nagiosadminpass
      - NAGIOS_TIMEZONE=America/New_York
    volumes:
      - ./nagios/etc:/opt/nagios/etc
      - ./nagios/var:/opt/nagios/var
      - ./nagios/plugins:/opt/nagios/plugins
      - ./nagios/objects:/opt/nagios/objects
      - ./nagios/init:/opt/nagios/init
